version: "3"
services:
        django:
            build: ./django
            networks:
                - overlay
            ports:
                - "8000:8000"
            volumes:
                - ./django:/code
            depends_on:
                - db
        
        db:
            build: ./db
            networks:
                    - overlay
            volumes:
                    - pgdata:/var/lib/postgresql/data
            environment:
                    POSTGRES_PASSWORD: postgres
            ports:
                    - "5432:5432"

        vue:
            build: ./vue
            networks: 
                - overlay
            volumes: 
                - './vue:/app'
                - 'vuedata:/app/node_modules'
            ports:
                - '80:8080'


volumes:
        pgdata:
        vuedata:
networks:
        overlay:
