# Generated by Django 3.0.8 on 2020-07-13 22:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200713_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='observation_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'observation types',
            },
        ),
        migrations.AlterModelOptions(
            name='map_data',
            options={'verbose_name_plural': 'map data'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'species'},
        ),
        migrations.AlterModelOptions(
            name='survey_data',
            options={'verbose_name_plural': 'survey data'},
        ),
        migrations.AlterModelOptions(
            name='survey_questions',
            options={'verbose_name_plural': 'survey questions'},
        ),
        migrations.AlterModelOptions(
            name='survey_template',
            options={'verbose_name_plural': 'survey templates'},
        ),
        migrations.CreateModel(
            name='incedent_observations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('public', models.BooleanField()),
                ('observation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.observation_type')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.species')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.app_user')),
            ],
        ),
    ]
