# Generated by Django 3.0.8 on 2020-07-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200713_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='latin_name',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
