# Generated by Django 3.0.8 on 2020-07-14 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200714_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='survey_method_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'survey method types',
            },
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['latin_name'], 'verbose_name_plural': 'species'},
        ),
        migrations.AlterField(
            model_name='map_data',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.CreateModel(
            name='survey_methods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=100)),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.survey_method_types')),
            ],
            options={
                'verbose_name_plural': 'survey methods',
                'unique_together': {('type_name', 'method_name')},
            },
        ),
    ]
