# Generated by Django 3.0.8 on 2020-07-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200714_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incedent_observations',
            options={'verbose_name_plural': 'incedent observations'},
        ),
    ]
